name: petcare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  shared_preferences: ^2.3.2
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
